# Generated by Django 5.0.1 on 2024-03-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prime',
            name='paie',
        ),
        migrations.AddField(
            model_name='prime',
            name='paies',
            field=models.ManyToManyField(blank=True, null=True, related_name='primes', to='payrolls.paie'),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(choices=[('CSG', 'CSG'), ('CRDS', 'CRDS'), ('CSA', 'CSA'), ('Cotisation Assurance maladie', 'Cotisation Assurance maladie'), ('Cotisation chomage', 'Cotisation chomage'), ('Cotisation retraite', 'Cotisation retraite')], default='CSG', max_length=255)),
                ('montant', models.FloatField()),
                ('taux', models.FloatField()),
                ('paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='payrolls.paie')),
            ],
        ),
    ]
