# Generated by Django 5.0.1 on 2024-03-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_delete_demandesft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enfant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=255)),
            ],
        ),
    ]
