# Generated by Django 5.0.1 on 2024-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_remove_prime_paie_prime_paies_cotisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisation',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='paie',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='paies',
            field=models.ManyToManyField(blank=True, null=True, related_name='cotisations', to='payrolls.paie'),
        ),
    ]
