# Generated by Django 5.0.1 on 2024-03-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payrolls', '0004_demandesft_date_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesft',
            name='membre_reversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_Sft', to='employees.agent'),
        ),
    ]
