# Generated by Django 5.0.1 on 2024-03-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_agent_contrat_alter_poste_agent'),
        ('payrolls', '0005_demandesft_membre_reversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesft',
            name='membre_reversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_Sft', to='employees.agent'),
        ),
        migrations.AlterField(
            model_name='indemnite',
            name='paie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indemnites', to='payrolls.paie'),
        ),
        migrations.AlterField(
            model_name='paie',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paies', to='employees.agent'),
        ),
    ]
