# Generated by Django 5.0.1 on 2024-03-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_apprenti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_stagiaire',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprenti', to='employees.agent')),
            ],
        ),
    ]
