# Generated by Django 5.0.1 on 2024-03-05 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_contrat', models.CharField(max_length=255)),
                ('type_contrat', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duree', models.IntegerField(default=0)),
                ('nb_heures', models.IntegerField(default=0)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
