# Generated by Django 5.0.1 on 2024-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Stage', 'Stage'), ('Apprentissage', 'Apprentissage')], default='CDI', max_length=255),
        ),
    ]
