# Generated by Django 5.0.1 on 2024-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contrat_type_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('Classique', [('CDD', 'CDD'), ('CDI', 'CDI')]), ('Spécifique', [('Urgent', 'Urgent'), ('Stage', 'Stage'), ('Apprentissage', 'Apprentissage')])], default='CDI', max_length=255),
        ),
    ]
