# Generated by Django 5.0.1 on 2024-03-12 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_declaration', models.CharField(max_length=255)),
                ('type_declaration', models.CharField(max_length=255)),
                ('pourcentage', models.FloatField()),
                ('montant', models.FloatField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='employees.agent')),
                ('paies', models.ManyToManyField(related_name='paies_declarations', to='payrolls.paie')),
            ],
        ),
    ]
