# Generated by Django 5.0.1 on 2024-02-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('statut', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=255)),
                ('date_embauche', models.DateField()),
                ('nb_enfants', models.IntegerField(default=0)),
                ('nb_heure', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_paie', models.CharField(max_length=255)),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('salaire_mois', models.FloatField()),
                ('salaire_annee', models.FloatField()),
                ('salaire_brute', models.FloatField()),
                ('salaire_net', models.FloatField()),
                ('agents', models.ManyToManyField(to='api.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('droit_NBI', models.BooleanField(default=False)),
                ('droit_ZUS', models.BooleanField(default=False)),
                ('droit_IFSE', models.BooleanField(default=False)),
                ('droit_CIA', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='api.agent')),
            ],
        ),
    ]
