# Generated by Django 5.0.1 on 2024-02-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_nom_agent_prenom_agent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
