# Generated by Django 5.0.1 on 2024-02-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agent_nom_alter_agent_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='agent',
        ),
    ]
