# Generated by Django 5.0.1 on 2024-02-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_poste_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='api.agent'),
        ),
    ]
