# Generated by Django 5.0.1 on 2024-02-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_poste_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_contrat', models.CharField(max_length=255)),
                ('type_contrat', models.CharField(max_length=255)),
                ('descripion', models.TextField()),
                ('duree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_prime', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paie',
            name='agents',
        ),
        migrations.AddField(
            model_name='paie',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='api.agent'),
        ),
        migrations.AddField(
            model_name='poste',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contrat'),
        ),
        migrations.CreateModel(
            name='Declarations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_declaration', models.CharField(max_length=255)),
                ('type_declaration', models.CharField(max_length=255)),
                ('pourcentage', models.FloatField()),
                ('montant', models.FloatField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='api.agent')),
                ('paies', models.ManyToManyField(related_name='paies_declarations', to='api.paie')),
            ],
        ),
    ]
