# Generated by Django 5.0.1 on 2024-03-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agent_conges_maladie_agent_conges_payes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='salaire_brute',
        ),
        migrations.AddField(
            model_name='prime',
            name='paie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='api.paie'),
        ),
    ]
