# Generated by Django 5.0.1 on 2024-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_paie_salaire_brute_prime_paie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
