# Generated by Django 5.0.1 on 2024-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_agent_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='agent',
            name='taux_cotisation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='taux_impot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
