# Generated by Django 5.0.1 on 2024-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_descripion_contrat_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='salaire_net',
        ),
        migrations.AlterField(
            model_name='agent',
            name='taux_cotisation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='taux_impot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
