# Generated by Django 5.0.1 on 2024-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_paie_salaire_net_alter_agent_taux_cotisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='taux_cotisation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='taux_impot',
            field=models.IntegerField(default=0),
        ),
    ]
