# Generated by Django 5.0.1 on 2024-03-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_agent_taux_cotisation_alter_agent_taux_impot'),
        ('employees', '0001_initial'),
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='agent',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='employees.agent'),
        ),
        migrations.RemoveField(
            model_name='prime',
            name='paie',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='paies',
            field=models.ManyToManyField(related_name='paies_declarations', to='payrolls.paie'),
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Paie',
        ),
        migrations.DeleteModel(
            name='Prime',
        ),
    ]
